### ISSUE TITLE
TrMenu2.0 的模板菜单 Example.yml 载入错误.

### ISSUE THREAD

**Issue by Score2** [Arasple/TrMenu#105]
很高兴看到 TrMenu 又更进了一步。我也满怀好奇对其进行了测试，但不幸的是，我遇到`TrMenu2.0 的模板菜单 Example.yml 载入错误.`。

错误如下：
```
[12:40:18 WARN]: Unexpected exception while parsing console command "trmenu reload"
org.bukkit.command.CommandException: Unhandled exception executing command 'trmenu' in plugin TrMenu v2.0
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:46) ~[NewPaper-1.12.2.jar:git-Paper-77cce823]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:152) ~[NewPaper-1.12.2.jar:git-Paper-77cce823]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchCommand(CraftServer.java:719) ~[NewPaper-1.12.2.jar:git-Paper-77cce823]
        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.dispatchServerCommand(CraftServer.java:682) ~[NewPaper-1.12.2.jar:git-Paper-77cce823]
        at net.minecraft.server.v1_12_R1.DedicatedServer.aP(DedicatedServer.java:463) ~[NewPaper-1.12.2.jar:git-Paper-77cce823]
        at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:424) ~[NewPaper-1.12.2.jar:git-Paper-77cce823]
        at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:774) ~[NewPaper-1.12.2.jar:git-Paper-77cce823]
        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:666) ~[NewPaper-1.12.2.jar:git-Paper-77cce823]
        at java.lang.Thread.run(Thread.java:819) [?:1.8.0_222]
Caused by: java.lang.IndexOutOfBoundsException: toIndex = 9
        at java.util.ArrayList.subListRangeCheck(ArrayList.java:1012) ~[?:1.8.0_222]
        at java.util.ArrayList.subList(ArrayList.java:1004) ~[?:1.8.0_222]
        at me.arasple.mc.trmenu.display.menu.MenuLayout$Companion.listIconsKeys(MenuLayout.kt:142) ~[?:?]
        at me.arasple.mc.trmenu.display.menu.MenuLayout$Companion.access$listIconsKeys(MenuLayout.kt:131) ~[?:?]
        at me.arasple.mc.trmenu.display.menu.MenuLayout$Layout.positionize(MenuLayout.kt:116) ~[?:?]
        at me.arasple.mc.trmenu.display.menu.MenuLayout.locateIcons(MenuLayout.kt:40) ~[?:?]
        at me.arasple.mc.trmenu.display.Menu.<init>(Menu.kt:22) ~[?:?]
        at me.arasple.mc.trmenu.modules.configuration.serialize.MenuSerializer.loadMenu(MenuSerializer.kt:29) ~[?:?]
        at me.arasple.mc.trmenu.TrMenuLoader$Companion.loadMenu(TrMenuLoader.kt:66) ~[?:?]
        at me.arasple.mc.trmenu.TrMenuLoader$Companion.loadMenus(TrMenuLoader.kt:56) ~[?:?]
        at me.arasple.mc.trmenu.commands.sub.CommandReload.onCommand(CommandReload.kt:15) ~[?:?]
        at io.izzel.taboolib.module.command.base.BaseMainCommand.onCommand(BaseMainCommand.java:166) ~[TabooLib.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) ~[NewPaper-1.12.2.jar:git-Paper-77cce823]
        ... 8 more
```
测试版本：Paper-1.12.2
其它有关插件：PlaceholderAPI（装有expansions：Player、Vault）

我不知道2.0版菜单的正确模板是怎样，因此我没有能力去修复这个错误的菜单。

**Comment by Arasple** [comment]
现在还处于早期开发阶段，请暂时不要自行测试
