### ISSUE TITLE
OP执行命令出错

### ISSUE THREAD

**Issue by BingZi-233** [Arasple/TrMenu#112]
# 以OP执行命令的时候存在问题

        [22:09:40] [Craft Scheduler Thread - 47/WARN]: [TrMenu] Plugin TrMenu v2.0 generated an exception while executing task 109073

        java.lang.IllegalStateException: PlayerCommandPreprocessEvent cannot be triggered asynchronously from another thread.

        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:572) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8ea9b13]

        at net.minecraft.server.v1_15_R1.PlayerConnection.handleCommand(PlayerConnection.java:1650) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8ea9b13]

        at net.minecraft.server.v1_15_R1.PlayerConnection.chat(PlayerConnection.java:1574) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8ea9b13]

        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftPlayer.chat(CraftPlayer.java:326) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8ea9b13]

        at me.arasple.mc.trmenu.modules.action.impl.ActionCommandOp.onExecute(ActionCommandOp.kt:16) ~[%5B太弱-菜单%5DTrMenu.jar:?]

        at me.arasple.mc.trmenu.modules.action.base.Action.run(Action.kt:37) ~[%5B太弱-菜单%5DTrMenu.jar:?]

        at me.arasple.mc.trmenu.modules.action.Actions$runActions$$inlined$forEach$lambda$2.run(Actions.kt:87) ~[%5B太弱-菜单%5DTrMenu.jar:?]

        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[spigot-1.15.2.jar:git-Spigot-a99063f-8ea9b13]

        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) [spigot-1.15.2.jar:git-Spigot-a99063f-8ea9b13]

        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_251]

        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_251]

        at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]

**Comment by Arasple** [comment]
已修复,下载最新构建
