### ISSUE TITLE
Can not support the placeholderAPI new version

### ISSUE THREAD

**Issue by TLeung094** [Arasple/TrMenu#113]
will show

`[23:44:36 WARN]: [TrMenu] Plugin TrMenu v1.22 generated an exception while executing task 973
java.lang.NoSuchMethodError: me.clip.placeholderapi.PlaceholderAPIPlugin.getExpansionCloud()Lme/clip/placeholderapi/expansion/cloud/ExpansionCloudManager;
    at me.arasple.mc.trmenu.menu.Menu.checkDepends(Menu.java:415) ~[?:?]
    at me.arasple.mc.trmenu.menu.Menu.setValues(Menu.java:97) ~[?:?]
    at me.arasple.mc.trmenu.menu.Menu.<init>(Menu.java:68) ~[?:?]
    at me.arasple.mc.trmenu.menu.MenuLoader.loadMenu(MenuLoader.java:232) ~[?:?]
    at me.arasple.mc.trmenu.menu.MenuLoader.lambda$null$0(MenuLoader.java:63) ~[?:?]
    at java.util.LinkedHashMap.forEach(Unknown Source) ~[?:1.8.0_261]
    at me.arasple.mc.trmenu.menu.MenuLoader.lambda$null$1(MenuLoader.java:63) ~[?:?]
    at java.util.ArrayList.forEach(Unknown Source) ~[?:1.8.0_261]
    at me.arasple.mc.trmenu.menu.MenuLoader.lambda$loadMenus$4(MenuLoader.java:61) ~[?:?]
    at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.1.jar:git-Paper-116]
    at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.16.1.jar:git-Paper-116]
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.16.1.jar:git-Paper-116]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_261]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_261]
    at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]`

**Comment by Arasple** [comment]
Fixed in the latest v2 build. v1 is no longer receiving support
