### ISSUE TITLE
关于HeadDatabase头颅的问题(v2)

### ISSUE THREAD

**Issue by Score2** [Arasple/TrMenu#114]
这应该也算遗留下来的问题了，自v1支持hdb后就没有修复。

当 hdb 插件未初始化完成时，也就是头颅没有完全载入时，TrMenu当读取到没有载入成功的头颅id时会不显示图标，虽然这是小问题，但体验不好，我给出两种修复方案：
* 搜索没有载入成功的头颅id的skull来显示
* 替换成史蒂夫头或自定义物品

> 另外, 我使用时也发现了相关问题的控制台报错，如下：
```
[00:18:49 WARN]: [TrMenu] Task #4119 for TrMenu v2.0 generated an exception
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909) ~[?:1.8.0_241]
        at java.util.ArrayList$Itr.next(ArrayList.java:859) ~[?:1.8.0_241]
        at me.arcaniax.hdb.HeadDatabaseManager.getHead(HeadDatabaseManager.java:409) ~[?:?]
        at me.arcaniax.hdb.api.HeadDatabaseAPI.getItemHead(HeadDatabaseAPI.java:39) ~[?:?]
        at me.arasple.mc.trmenu.modules.hook.HookHeadDatabase.getHead(HookHeadDatabase.kt:31) ~[?:?]
        at me.arasple.mc.trmenu.display.item.property.Mat.createItem(Mat.kt:44) ~[?:?]
        at me.arasple.mc.trmenu.display.item.DynamicItem.releaseItem(DynamicItem.kt:34) ~[?:?]
        at me.arasple.mc.trmenu.display.icon.IconDisplay.createDisplayItem(IconDisplay.kt:23) ~[?:?]
        at me.arasple.mc.trmenu.display.Icon$displayItemStack$1.run(Icon.kt:44) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftTask.run(CraftTask.java:99) ~[NewPaper-1.16.1.jar:git-Paper-dc80610f]
        at org.bukkit.craftbukkit.v1_16_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[NewPaper-1.16.1.jar:git-Paper-dc80610f]
        at net.minecraft.server.v1_16_R1.MinecraftServer.b(MinecraftServer.java:1291) ~[NewPaper-1.16.1.jar:git-Paper-dc80610f]
        at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:377) ~[NewPaper-1.16.1.jar:git-Paper-dc80610f]
        at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212) ~[NewPaper-1.16.1.jar:git-Paper-dc80610f]
        at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000) ~[NewPaper-1.16.1.jar:git-Paper-dc80610f]
        at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[NewPaper-1.16.1.jar:git-Paper-dc80610f]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
```
#### 重现方式：
* 在 hdb 插件未完全载入时打开菜单。

**Comment by Arasple** [comment]
Fixed in the latest v2 build
