### ISSUE TITLE
Error while Disabling TrMenu v2.0

### ISSUE THREAD

**Issue by SrBedrock** [Arasple/TrMenu#118]
### Error:

```
[08:02:21 INFO]: [TrMenu] Disabling TrMenu v2.0
[08:02:21 WARN]: java.lang.reflect.InvocationTargetException
[08:02:21 WARN]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[08:02:21 WARN]: at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[08:02:21 WARN]: at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[08:02:21 WARN]: at java.base/java.lang.reflect.Method.invoke(Method.java:564)
[08:02:21 WARN]: at io.izzel.taboolib.util.Reflection.invokeMethod(Reflection.java:160)
[08:02:21 WARN]: at io.izzel.taboolib.module.inject.TInjectCreator.eval(TInjectCreator.java:75)
[08:02:21 WARN]: at io.izzel.taboolib.module.inject.TInjectCreator.unload(TInjectCreator.java:48)
[08:02:21 WARN]: at io.izzel.taboolib.TabooLibLoader.lambda$unloadClass$6(TabooLibLoader.java:171)
[08:02:21 WARN]: at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
[08:02:21 WARN]: at io.izzel.taboolib.TabooLibLoader.unloadClass(TabooLibLoader.java:168)
[08:02:21 WARN]: at io.izzel.taboolib.PluginLoader$1.onStopping(PluginLoader.java:95)
[08:02:21 WARN]: at io.izzel.taboolib.PluginLoader.lambda$stop$5(PluginLoader.java:155)
[08:02:21 WARN]: at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
[08:02:21 WARN]: at io.izzel.taboolib.PluginLoader.stop(PluginLoader.java:155)
[08:02:21 WARN]: at me.arasple.mc.trmenu.boot.Plugin.onDisable(Plugin.java:93)
[08:02:21 WARN]: at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:265)
[08:02:21 WARN]: at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:415)
[08:02:21 WARN]: at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:516)
[08:02:21 WARN]: at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:502)
[08:02:21 WARN]: at org.bukkit.plugin.SimplePluginManager.disablePlugins(SimplePluginManager.java:495)
[08:02:21 WARN]: at org.bukkit.craftbukkit.v1_16_R1.CraftServer.disablePlugins(CraftServer.java:434)
[08:02:21 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.stop(MinecraftServer.java:775)
[08:02:21 WARN]: at net.minecraft.server.v1_16_R1.DedicatedServer.stop(DedicatedServer.java:700)
[08:02:21 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1048)
[08:02:21 WARN]: at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
[08:02:21 WARN]: at java.base/java.lang.Thread.run(Thread.java:832)
[08:02:21 WARN]: Caused by: java.lang.NoSuchMethodError: 'me.clip.placeholderapi.expansion.manager.LocalExpansionManager me.clip.placeholderapi.PlaceholderAPIPlugin.getLocalExpansionManager()'
[08:02:21 WARN]: at me.arasple.mc.trmenu.TrMenuLoader.cancel(TrMenuLoader.kt:43)
[08:02:21 WARN]: ... 26 more
```

**Comment by Arasple** [comment]
Try to update your PlaceholderAPI to the latest version

**Comment by Sikatsu** [comment]
Updating PlaceholderAPI to the latest version breaks a lot of placeholders for me, so isn't really an option until those expansions are updated. No other way to get rid of this error? ^^

**Comment by Arasple** [comment]
> Updating PlaceholderAPI to the latest version breaks a lot of placeholders for me, so isn't really an option until those expansions are updated. No other way to get rid of this error? ^^

Could you try to update PlaceholderAPI to `2.10.8`, which is likely no longer going to break any placeholders now
