### ISSUE TITLE
1.15.1paper 1.11tr 按文档执行-'close' 提示warn

### ISSUE THREAD

**Issue by imjtq** [Arasple/TrMenu#12]
[17:52:26] [Craft Scheduler Thread - 1/WARN]: [TrMenu] Plugin TrMenu v1.11-R2 generated an exception while executing task 120
java.lang.IllegalStateException: InventoryCloseEvent may only be triggered synchronously.
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:533) ~[patched_1.15.1.jar:git-Paper-26]
	at org.bukkit.craftbukkit.v1_15_R1.event.CraftEventFactory.handleInventoryCloseEvent(CraftEventFactory.java:1369) ~[patched_1.15.1.jar:git-Paper-26]
	at net.minecraft.server.v1_15_R1.EntityPlayer.closeInventory(EntityPlayer.java:1235) ~[patched_1.15.1.jar:git-Paper-26]
	at org.bukkit.craftbukkit.v1_15_R1.entity.CraftHumanEntity.closeInventory(CraftHumanEntity.java:623) ~[patched_1.15.1.jar:git-Paper-26]
	at me.arasple.mc.trmenu.action.acts.ActionClose.onExecute(ActionClose.java:19) ~[?:?]
	at me.arasple.mc.trmenu.action.base.AbstractAction.run(AbstractAction.java:53) ~[?:?]
	at me.arasple.mc.trmenu.action.TrAction.lambda$runActions$1(TrAction.java:57) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.1.jar:git-Paper-26]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.1.jar:git-Paper-26]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.1.jar:git-Paper-26]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_201]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]

**Comment by Arasple** [comment]
fixed, pls download v1.11-R3
