### ISSUE TITLE
希望能增加可以添加MOD材质以及NBT自定义MOD图标位置的功能

### ISSUE THREAD

**Issue by 850416511** [Arasple/TrMenu#15]
MOD材质可以自己制作替换更具标志性的图标，提高玩家辨识度。

自定义MOD图标位置可以方便自己定位添加MOD的材质，比如添加神奇宝贝mod里面的精灵照片材质。

      ItemType = "pixelmon:pixelmon_sprite"
      UnsafeDamage = 0
	  UnsafeData = {
       SpriteName = "pixelmon:sprites/pokemon/786"
      }
         

感谢付出。

**Comment by Arasple** [comment]
当前情况下，使用 Mod 物品的 ID，能支持吗？

**Comment by 850416511** [comment]
不清楚是不是我格式问题。我试了很多次都不可以



---原始邮件---
发件人: "Arasple"<notifications@github.com&gt;
发送时间: 2020年1月16日(周四) 中午11:14
收件人: "Arasple/TrMenu"<TrMenu@noreply.github.com&gt;;
抄送: "Author"<author@noreply.github.com&gt;;"850416511"<1062447360@QQ.COM&gt;;
主题: Re: [Arasple/TrMenu] 希望能增加可以添加MOD材质以及NBT自定义MOD图标位置的功能 (#15)



当前情况下，使用 Mod 物品的 ID，能支持吗？

**Comment by Arasple** [comment]
我试了下是可以的，你可以下载测试下这个版本

![1](https://user-images.githubusercontent.com/35389235/72492389-fa3f8b00-3857-11ea-979c-2976c4a2e200.png)
![2](https://user-images.githubusercontent.com/35389235/72492390-fad82180-3857-11ea-9e14-dd6127fb22b3.png)

[TrMenu-1.12-R4-pre1.zip](https://github.com/Arasple/TrMenu/files/4069260/TrMenu-1.12-R4-pre1.zip)

**Comment by 850416511** [comment]
可以用MOD 材质了，但是这边有个报错。
[13:04:51] [Craft Scheduler Thread - 38/WARN]: [PlaceholderAPI] Plugin PlaceholderAPI v2.10.4 generated an exception while executing task 413
java.lang.NullPointerException: null
        at me.clip.placeholderapi.expansion.cloud.ExpansionCloudManager.lambda$null$3(ExpansionCloudManager.java:181) ~[?:?]
        at java.util.Map.forEach(Unknown Source) ~[?:1.8.0_231]
        at me.clip.placeholderapi.expansion.cloud.ExpansionCloudManager.lambda$fetch$4(ExpansionCloudManager.java:172) ~[?:?]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:76) ~[CraftTask.class:git-CatServer-1.12.2-477570a]
        at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52) [CraftAsyncTask.class:git-CatServer-1.12.2-477570a]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_231]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_231]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_231]
