### ISSUE TITLE
TabooLib failed to load

### ISSUE THREAD

**Issue by fichdlmaa** [Arasple/TrMenu#21]
SpigotMC 1.14.4 latest release
TrMenu | 1.8-1.15 1.13 R3

LogFile Excerpt:

....
[20:10:20] [Server thread/INFO]: [0;37;1m[TabooLib] [0;37;22mDownloading TabooLib (Tr Plugin's dependency)...[m
[20:10:26] [Server thread/WARN]: java.lang.ClassCastException: Cannot cast jdk.internal.loader.ClassLoaders$AppClassLoader to java.net.URLClassLoader
[20:10:26] [Server thread/WARN]: 	at java.base/java.lang.Class.cast(Class.java:3605)
[20:10:26] [Server thread/WARN]: 	at me.arasple.mc.trmenu.TrMenuPlugin$Loader.addPath(TrMenuPlugin.java:538)
[20:10:26] [Server thread/WARN]: 	at me.arasple.mc.trmenu.TrMenuPlugin.init(TrMenuPlugin.java:335)
[20:10:26] [Server thread/WARN]: 	at me.arasple.mc.trmenu.TrMenuPlugin.<clinit>(TrMenuPlugin.java:65)
[20:10:26] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[20:10:26] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:398)
[20:10:26] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:59)
[20:10:26] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:135)
[20:10:26] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:334)
[20:10:26] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:253)
[20:10:26] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_14_R1.CraftServer.loadPlugins(CraftServer.java:350)
[20:10:26] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.DedicatedServer.init(DedicatedServer.java:202)
[20:10:26] [Server thread/WARN]: 	at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:775)
[20:10:26] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[20:10:26] [Server thread/INFO]: [0;31;22m[TabooLib] [0;31;1mFailed to load.[m
...

**Comment by Arasple** [comment]
Please change to JDK 8
