### ISSUE TITLE
TrMenu在Akarin服务端无法启动

### ISSUE THREAD

**Issue by TSIXS** [Arasple/TrMenu#30]
請支持 Akarin 服務端
TrMenu在Akarin服务端无法启动，报错如下：
```
[20:10:52 WARN]: java.lang.NoSuchFieldException: ucp
[20:10:52 WARN]:        at java.lang.Class.getDeclaredField(Class.java:2070)
[20:10:52 WARN]:        at me.arasple.mc.trmenu.Plugin$Loader.addPath(Plugin.java:675)
[20:10:52 WARN]:        at me.arasple.mc.trmenu.Plugin.init(Plugin.java:399)
[20:10:52 WARN]:        at me.arasple.mc.trmenu.Plugin.<clinit>(Plugin.java:151)
[20:10:52 WARN]:        at java.lang.Class.forName0(Native Method)
[20:10:52 WARN]:        at java.lang.Class.forName(Class.java:348)
[20:10:52 WARN]:        at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:82)
[20:10:52 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:127)
[20:10:52 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:333)
[20:10:52 WARN]:        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:255)
[20:10:52 WARN]:        at org.bukkit.craftbukkit.v1_12_R1.CraftServer.loadPlugins(CraftServer.java:321)
[20:10:52 WARN]:        at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:222)
[20:10:52 WARN]:        at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
[20:10:52 WARN]:        at java.lang.Thread.run(Thread.java:748)
[20:10:52 INFO]: [TabooLib] 主运行库未完成初始化, 插件停止加载.
```

**Comment by Arasple** [comment]
Akarin 都弃坑了，不提供支持

**Comment by TSIXS** [comment]
> Akarin 都弃坑了，不提供支持

在1.12.2的项目已经停止，但1.13.2的仍然继续在更新。https://circleci.com/gh/Akarin-project/Akarin
虽然1.12.2项目已经弃坑，但作为多线程服务端，其性能还是不错的，希望能够支持
