### ISSUE TITLE
ItemFlags errors

### ISSUE THREAD

**Issue by BackWheel** [Arasple/TrMenu#47]
当这款插件在我服务器运行的时候，它经常会出现这样的warm

[12:01:02 WARN]: [TrMenu] Plugin TrMenu v1.18 generated an exception while executing task 252933
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_241]
        at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_241]
        at me.arasple.mc.trmenu.display.Item.createItemStack(Item.java:98) ~[?:?]
        at me.arasple.mc.trmenu.menu.Menu.setButton(Menu.java:267) ~[?:?]
        at me.arasple.mc.trmenu.menu.Menu.access$200(Menu.java:41) ~[?:?]
        at me.arasple.mc.trmenu.menu.Menu$4.run(Menu.java:260) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-112]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-112]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-112]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_241]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[12:01:02 WARN]: [TrMenu] Plugin TrMenu v1.18 generated an exception while executing task 10725269
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_241]
        at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_241]
        at me.arasple.mc.trmenu.display.Item.createItemStack(Item.java:98) ~[?:?]
        at me.arasple.mc.trmenu.menu.Menu.setButton(Menu.java:267) ~[?:?]
        at me.arasple.mc.trmenu.menu.Menu.access$200(Menu.java:41) ~[?:?]
        at me.arasple.mc.trmenu.menu.Menu$4.run(Menu.java:260) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-112]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-112]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-112]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_241]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]
[12:01:02 WARN]: [TrMenu] Plugin TrMenu v1.18 generated an exception while executing task 252933
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$Itr.checkForComodification(Unknown Source) ~[?:1.8.0_241]
        at java.util.ArrayList$Itr.next(Unknown Source) ~[?:1.8.0_241]
        at me.arasple.mc.trmenu.display.Item.createItemStack(Item.java:98) ~[?:?]
        at me.arasple.mc.trmenu.menu.Menu.setButton(Menu.java:267) ~[?:?]
        at me.arasple.mc.trmenu.menu.Menu.access$200(Menu.java:41) ~[?:?]
        at me.arasple.mc.trmenu.menu.Menu$4.run(Menu.java:260) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-112]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-112]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-112]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_241]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

**Comment by Arasple** [comment]
Fixed in v1.19
