### ISSUE TITLE
插件运行警告

### ISSUE THREAD

**Issue by BackWheel** [Arasple/TrMenu#57]
[17:59:05 WARN]: [TrMenu] Plugin TrMenu v1.19 generated an exception while executing task 15135304
java.util.ConcurrentModificationException: null
        at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.copyInto(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.AbstractPipeline.evaluate(Unknown Source) ~[?:1.8.0_241]
        at java.util.stream.ReferencePipeline.forEach(Unknown Source) ~[?:1.8.0_241]
        at me.arasple.mc.trmenu.display.Item.createItemStack(Item.java:99) ~[?:?]
        at me.arasple.mc.trmenu.menu.Menu.setButton(Menu.java:267) ~[?:?]
        at me.arasple.mc.trmenu.menu.Menu$4.run(Menu.java:260) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-118]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-118]
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-118]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_241]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_241]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_241]

**Comment by Arasple** [comment]
fixed in v1.21
