### ISSUE TITLE
BUG:REQUIREMENT条件无法正常使用

### ISSUE THREAD

**Issue by RusBrook** [Arasple/TrMenu#6]
服务器核心: spigot-1.8.8
插件列表:
Taboolib
Trmenu
PlaceholderAPI
Vault
问题:
REQUIREMENT条件无法正常使用
<REQUIREMENT:%vault_eco_balance% == 10>可正常使用
<REQUIREMENT:%vault_eco_balance% >= 10>无法使用
<REQUIREMENT:%vault_eco_balance% <= 10>无法使用
出问题配置:
        actions:
          all:
            - 'close'
            - 'tell: &8[&3系统&8]:&c金币不足&a10&c点,无法兑换.<REQUIREMENT:%vault_eco_balance% >= 10>'
后台报错信息:
[13:33:22 ERROR]: Could not pass event InventoryClickEvent to TrMenu v1.06
org.bukkit.event.EventException
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:310) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-5f38d38-12698ea]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.jav
a:62) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-5f38d38-12698ea]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.j
ava:502) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-5f38d38-12698ea]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.j
ava:487) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-5f38d38-12698ea]
        at com.ilummc.tlib.inject.TPluginManager.callEvent(TPluginManager.java:1
32) [TabooLib-4.9.jar:?]
        at net.minecraft.server.v1_8_R3.PlayerConnection.a(PlayerConnection.java
:1630) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:31)
 [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.PacketPlayInWindowClick.a(SourceFile:9)
[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.PlayerConnectionUtils$1.run(SourceFile:1
3) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-5f38d38-12698ea]
        at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [
?:1.8.0_151]
        at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.8.0_151]
        at net.minecraft.server.v1_8_R3.SystemUtils.a(SourceFile:44) [spigot-1.8
.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:7
15) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:3
74) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:6
54) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-5f38d38-12698ea]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java
:557) [spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-5f38d38-12698ea]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_151]
Caused by: java.lang.ClassCastException: java.lang.Double cannot be cast to java
.lang.Boolean
        at me.arasple.mc.trmenu.actions.ActionRunner.isRequirementMatch(ActionRu
nner.java:116) ~[?:?]
        at me.arasple.mc.trmenu.actions.ActionRunner.lambda$runActions$1(ActionR
unner.java:48) ~[?:?]
        at java.util.HashMap.forEach(Unknown Source) ~[?:1.8.0_151]
        at me.arasple.mc.trmenu.actions.ActionRunner.runActions(ActionRunner.jav
a:47) ~[?:?]
        at me.arasple.mc.trmenu.actions.ActionRunner.runActions(ActionRunner.jav
a:32) ~[?:?]
        at me.arasple.mc.trmenu.listeners.ListenerMenuAction.onClick(ListenerMen
uAction.java:66) ~[?:?]
        at sun.reflect.GeneratedMethodAccessor171.invoke(Unknown Source) ~[?:?]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1
.8.0_151]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_151]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.ja
va:306) ~[spigot-1.8.8-R0.1-SNAPSHOT-latest.jar:git-Spigot-5f38d38-12698ea]
        ... 16 more

**Comment by Arasple** [comment]
感谢反馈，会被修复的 :)

**Comment by Arasple** [comment]
已修复，请下载使用 v1.07

**Comment by RusBrook** [comment]
1.12.2依然存在此问题

**Comment by RusBrook** [comment]
> 已修复，请下载使用v1.07

1.12.2依然存在此问题

**Comment by Arasple** [comment]
may fixed,

https://github.com/Arasple/TrMenu/issues/7
