### ISSUE TITLE
/trmenu template and share not working

### ISSUE THREAD

**Issue by Tanguygab** [Arasple/TrMenu#84]
Hey, I and others found out that the commands `/trmenu template` and `/trmenu share` don't work anymore
 
It seems weird to me because they worked perfectly like 3-5 days ago or something like that, so maybe it's an issue with Hastebin.com ?
here's what I get in console:
- for `/trmenu share`
```[TrMenu] Plugin TrMenu v1.21 generated an exception while executing task 91
java.lang.NullPointerException: null
	at me.arasple.mc.trmenu.commands.CommandShare.lambda$onCommand$0(CommandShare.java:46) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-213]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-213]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-213]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_251]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
[TrMenu] Plugin TrMenu v1.21 generated an exception while executing task 86
java.lang.NullPointerException: null
	at me.arasple.mc.trmenu.commands.CommandTemplate.lambda$onCommand$1(CommandTemplate.java:59) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-213]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-213]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-213]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_251]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
```  
- and for `/trmenu template`
```[TrMenu] Plugin TrMenu v1.21 generated an exception while executing task 86
java.lang.NullPointerException: null
	at me.arasple.mc.trmenu.commands.CommandTemplate.lambda$onCommand$1(CommandTemplate.java:59) ~[?:?]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-213]
	at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-213]
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-213]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [?:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [?:1.8.0_251]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_251]
```

**Comment by Tanguygab** [comment]
I guess it was from Hastebin because they work now =)
