### ISSUE TITLE
Template creator gets stuck

### ISSUE THREAD

**Issue by MoonSoD** [Arasple/TrMenu#86]
After creating a template using the `/trmenu template` command the process just gets stuck on the  `Generate into inventory format ...` message

![creationMessage](https://cdn.discordapp.com/attachments/668430616634851329/704066148379000862/unknown.png)

The error accompanied with it:
```
 [22:21:05 WARN]: [TrMenu] Plugin TrMenu v1.21 generated an exception while executing task 2239734
java.lang.NullPointerException: null
at me.arasple.mc.trmenu.commands.CommandTemplate.lambda$onCommand$1(CommandTemplate.java:59) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[minecraft_server.jar:git-Purpur-d02efdf]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[minecraft_server.jar:git-Purpur-d02efdf]
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[minecraft_server.jar:git-Purpur-d02efdf]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_241]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_241]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_241]
```

**Comment by Tanguygab** [comment]
I thought it has been resolved :thinking:
It isn't from TrMenu tho, it's Hastebin doing weird things. I don't think that TrMenu can do anything about it
