### ISSUE TITLE
最新1.15.1 paper端不生成trmenu插件文件夹不能使用

### ISSUE THREAD

**Issue by MintSkye** [Arasple/TrMenu#9]
刚启动服务器的时候刷如下报错：
[02:58:29] [Server thread/WARN]: java.lang.ClassCastException: Cannot cast jdk.internal.loader.ClassLoaders$AppClassLoader to java.net.URLClassLoader
[02:58:29] [Server thread/WARN]: 	at java.base/java.lang.Class.cast(Class.java:3605)
[02:58:29] [Server thread/WARN]: 	at me.arasple.mc.trmenu.TrMenuPlugin$Loader.addPath(TrMenuPlugin.java:539)
[02:58:29] [Server thread/WARN]: 	at me.arasple.mc.trmenu.TrMenuPlugin.init(TrMenuPlugin.java:335)
[02:58:29] [Server thread/WARN]: 	at me.arasple.mc.trmenu.TrMenuPlugin.<clinit>(TrMenuPlugin.java:65)
[02:58:29] [Server thread/WARN]: 	at java.base/java.lang.Class.forName0(Native Method)
[02:58:29] [Server thread/WARN]: 	at java.base/java.lang.Class.forName(Class.java:398)
[02:58:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:63)
[02:58:29] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134)
[02:58:29] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:337)
[02:58:29] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:257)
[02:58:29] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_15_R1.CraftServer.loadPlugins(CraftServer.java:356)
[02:58:29] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:226)
[02:58:29] [Server thread/WARN]: 	at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:884)
[02:58:29] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:834)
[02:58:29] [Server thread/INFO]: [TabooLib] 主运行库未完成初始化, 插件停止加载.
无trmenu插件文件夹生成，但是log里却提示enable了，关服时也有disable的提示。

**Comment by Arasple** [comment]
pls re-dl TrMenu v1.1 try again
